//*****************************************************************************
//
// Base Address mapping for peripherals with FrameSel support
//
//*****************************************************************************
#define ADCA_BASE  ADCA_BASE_FRAME(0)
#define EPWM1_BASE  EPWM1_BASE_FRAME(0)
#define EPWM1XCMP_BASE  EPWM1XCMP_BASE_FRAME(0)
#define EPWM1DE_BASE  EPWM1DE_BASE_FRAME(0)
#define EPWM1MINDBLUT_BASE  EPWM1MINDBLUT_BASE_FRAME(0)
#define EPWM1XLINK_BASE  EPWM1XLINK_BASE_FRAME(0)
#define EPWM1XCMPXLINK_BASE  EPWM1XCMPXLINK_BASE_FRAME(0)
#define EPWM1DEXLINK_BASE  EPWM1DEXLINK_BASE_FRAME(0)
#define EPWM1MINDBLUTXLINK_BASE  EPWM1MINDBLUTXLINK_BASE_FRAME(0)
#define EPWM2_BASE  EPWM2_BASE_FRAME(0)
#define EPWM2XCMP_BASE  EPWM2XCMP_BASE_FRAME(0)
#define EPWM2DE_BASE  EPWM2DE_BASE_FRAME(0)
#define EPWM2MINDBLUT_BASE  EPWM2MINDBLUT_BASE_FRAME(0)
#define EPWM2XLINK_BASE  EPWM2XLINK_BASE_FRAME(0)
#define EPWM2XCMPXLINK_BASE  EPWM2XCMPXLINK_BASE_FRAME(0)
#define EPWM2DEXLINK_BASE  EPWM2DEXLINK_BASE_FRAME(0)
#define EPWM2MINDBLUTXLINK_BASE  EPWM2MINDBLUTXLINK_BASE_FRAME(0)
#define UARTA_BASE  UARTA_BASE_FRAME(0)
